-- =========================================================================================
-- MIGRATION: ADD PROGRESS TRACKING
-- =========================================================================================

-- 1. ALTER TABLE transaksi to add progress_status
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='transaksi' AND column_name='progress_status') THEN
        ALTER TABLE public.transaksi ADD COLUMN progress_status text DEFAULT 'Menunggu Material' NOT NULL;
    END IF;
END $$;

-- 2. CREATE TABLE transaksi_history
CREATE TABLE IF NOT EXISTS public.transaksi_history (
    id bigint generated by default as identity primary key,
    transaksi_id bigint references public.transaksi(id) on delete cascade not null,
    status_progress text not null,
    pesan text,
    created_at timestamp with time zone default now() not null
);

-- 3. UPDATE RLS on transaksi_history
ALTER TABLE public.transaksi_history ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "history_select" ON public.transaksi_history;
DROP POLICY IF EXISTS "history_insert_umkm" ON public.transaksi_history;

-- Select policy: users related to the transaction can read its history
CREATE POLICY "history_select" ON public.transaksi_history FOR SELECT TO authenticated
USING (
    EXISTS (
        SELECT 1 FROM public.transaksi t
        JOIN public.request r ON t.request_id = r.id
        LEFT JOIN public.umkm u ON r.umkm_id = u.id
        LEFT JOIN public.industri i ON r.industri_id = i.id
        WHERE t.id = transaksi_history.transaksi_id
        AND (u.user_id = auth.uid() OR i.user_id = auth.uid() OR public.is_admin())
    )
);

-- Insert policy: only UMKM can insert history for their own transaction
CREATE POLICY "history_insert_umkm" ON public.transaksi_history FOR INSERT TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1 FROM public.transaksi t
        JOIN public.request r ON t.request_id = r.id
        JOIN public.umkm u ON r.umkm_id = u.id
        WHERE t.id = transaksi_history.transaksi_id
        AND u.user_id = auth.uid()
    )
);
